#!/bin/bash
echo "ARRAY.min"
./phase2 < array.min > array2.mil
./mil_run array2.mil
echo "FIB_ARRAY.min"
./phase2 < fib_array.min > fib_array2.mil
./mil_run fib_array2.mil
echo "FUNCTION.min"
./phase2 < function.min > function2.mil
./mil_run function2.mil
echo "ERROR_TEST.min"
./phase2 < error_test.min > error_test.mil
cat error_test.mil
echo "LOOP.min"
./phase2 < loop.min > loop2.mil
./mil_run loop2.mil
echo "IFELSE.min"
./phase2 < ifelse.min > ifelse2.mil
./mil_run ifelse2.mil
echo "CONTINUE.min"
./phase2 < continue.min > continue2.mil
./mil_run continue2.mil
echo "NESTED_LOOP.min"
./phase2 < nested_loop.min > nested_loop2.mil
./mil_run nested_loop2.mil